name: Verify Build

on:
  push:
      paths:
        - "build.gradle"
        - "settings.gradle"
        - "gradle.properties"
        - "gradle-wrapper.properties"
        - "gradlew"
        - "gradlew.bat"
        - "src/**"
        - ".github/workflows/build.yml"
  pull_request:
  workflow_dispatch:

jobs:
  verification:
    name: Verification
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
      - name: Build with Gradle
        run: ./gradlew build run
