name: Eclipse XText BVS Experiment

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/experiment-eclipse-xtext.yml"

env:
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"
  GIT_REPO: "https://github.com/ribafish/xtext.git"
  BRANCH: "feature/develocity"
  ARGS: "-Dscan.tag.gk-eclipse-exp"

jobs:
  Experiment:
    strategy:
      fail-fast: false
      matrix:
        goals:
          - "install -DskipTests=true -Dscan.tag.skipTests"
          - "install"
          - "verify -f org.eclipse.xtext.full.releng -B -fae -PuseJenkinsSnapshots -Pstrict-jdk-21"
        experimentId: [1, 2]
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
      - name: Set Maven Home environment variable
        run: echo "MAVEN_WRAPPER_HOME=$(./mvnw --version | grep "Maven home:" | cut -c 13-)" >> "$GITHUB_ENV"
      - name: Download latest version of the validation scripts
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/download@actions-stable
        with:
          downloadDevelopmentRelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run experiment 1
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/experiment-1@actions-stable
        if: matrix.experimentId == 1
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ matrix.goals }}
          args: ${{ env.ARGS }} "-Dmaven.home=${{ env.MAVEN_WRAPPER_HOME }}"
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          gitBranch: ${{ env.BRANCH }}
          failIfNotFullyCacheable: false
          enableDevelocity: false
          enableGradleEnterprise: false
      - name: Run experiment 2
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/experiment-2@actions-stable
        if: matrix.experimentId == 2
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ matrix.goals }}
          args: ${{ env.ARGS }} "-Dmaven.home=${{ env.MAVEN_WRAPPER_HOME }}"
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          gitBranch: ${{ env.BRANCH }}
          failIfNotFullyCacheable: false
          enableDevelocity: false
          enableGradleEnterprise: false