name: Eclipse JDT-Core BVS Experiment

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/experiment-eclipse-jdt-core.yml"

env:
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"
  GIT_REPO: "https://github.com/eclipse-jdt/eclipse.jdt.core.git"
  ARGS: "-Dscan.tag.gk-eclipse-exp"

jobs:
  Experiment:
    strategy:
      fail-fast: false
      matrix:
        goals:
          - "install -DskipTests=true -Dscan.tag.skipTests"
          - "install --batch-mode -f org.eclipse.jdt.core.compiler.batch -DlocalEcjVersion=99.99"
          - "verify --batch-mode --fail-at-end -Ptest-on-javase-21 -Pbree-libs -Papi-check -Djava.io.tmpdir=$WORKSPACE/tmp -Dproject.build.sourceEncoding=UTF-8 -Dtycho.surefire.argLine=\"--add-modules ALL-SYSTEM -Dcompliance=1.8,11,17,20 -Djdt.performance.asserts=disabled\" -Dcbi-ecj-version=99.99"
        experimentId: [1, 2]
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDKs ☕
        uses: actions/setup-java@v4
        with:
          java-version: |
            8
            17
            21
          mvn-toolchain-id: |
            JavaSE-1.8
            JavaSE-17
            JavaSE-21
          distribution: 'temurin'
      - name: Download latest version of the validation scripts
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/download@actions-stable
        with:
          downloadDevelopmentRelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run experiment 1
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/experiment-1@actions-stable
        if: matrix.experimentId == 1
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ matrix.goals }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: false
          enableDevelocity: true
          enableGradleEnterprise: true
      - name: Run experiment 2
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/experiment-2@actions-stable
        if: matrix.experimentId == 2
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ matrix.goals }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: false
          enableDevelocity: true
          enableGradleEnterprise: true